### ISSUE TITLE
Invoke-RestMethod -Method PUT fails

### ISSUE THREAD

**Issue by arcotek-ltd** [Mexia/PowerShell#1]
Hi @mattcorr,

Firstly, thank you for this elegant solution. Interesting to know TeamCity has this covered. I've often struggled with the best way to handle versioning PS modules and this seems like an elegant solution.

I'm not sure if MS have moved the goal posts (yet again), or I have something turned on / off in my VSTS, however, I was getting the error:
```
Invoke-RestMethod : {"$id":"1","innerException":null,"message":"No api-version was supplied for the \"PUT\" request. 
2018-04-21T00:16:32.2687689Z The version must be supplied either as part of the Accept header (e.g. \"application/json; api-version=1.0\") or as a 
2018-04-21T00:16:32.2687848Z query parameter (e.g. 
2018-04-21T00:16:32.2687996Z \"?api-version=1.0\")."
```

Checking the contents of `-Uri` in the PUT, I found `"$($projectDef.Url)?api-version=2.0"` resolved to:

```
https://myvsts.visualstudio.com/430d1f32-13e0-4863-b322-717b7483832f/_apis/build/Definitions/1?revision=101?api-version=2.0
```
So there is already a query parameter in the URI. (`?revision=101`).

All I had to do was change the `?` to `&` for the `-Uri` parameter thus becoming:
```
"$($projectDef.Url)&api-version=2.0"
```

Thanks again.

**Comment by mattcorr** [comment]
Hmm thats interesting. Just have to ensure there is a `?` first, followed by `&` for each additional URL parameter.
Will have to look into that. Thanks!

**Comment by mattcorr** [comment]
Have updated my script to check if the api version is the only or an additional parameter. Thanks for bringing this to my attention @arcotek-ltd
