### ISSUE TITLE
Linked Variables removed when code called in VSTS

### ISSUE THREAD

**Issue by arcotek-ltd** [Mexia/PowerShell#3]
Hi @mattcorr,

I've got a very strange issue that I suspect is more to do with the API than anything in your code. In brief, when the task runs that contains your code, it unlinks my "variable group".

I am running the build agent as a service account and the PAT has been generated using that service account. (I have tried using the `NT AUTHORITY\NETWORK SERVICE` account and my VSTS user - with the same result).

I've logged a ticket / reported the issue [here](https://developercommunity.visualstudio.com/content/problem/239654/vsts-build-tasks-not-saving-and-unlinking-variable.html?childToView=242738#comment-242738), but was wondering if you may have any insight as to what is going on?

Thanks

**Comment by arcotek-ltd** [comment]
Sorry, it was me being stupid. I'd updated the code to use API version 4.1, but forgot to copy it to the build server, so it was using API 2.0. The update to use API 4.1 resolved the issue.

**Comment by mattcorr** [comment]
Glad its all sorted!
